@extends('layouts.app')
@section('title', 'Input Penilaian')
@section('page-title', 'Input Penilaian')
@section('page-subtitle', 'Isi nilai riil setiap alternatif terhadap seluruh kriteria')
@section('content')
<div class="card mb-4"><div class="card-body d-flex flex-column flex-lg-row gap-3 align-items-lg-center justify-content-between"><div><h5 class="fw-bold mb-1">Matriks Keputusan Dinamis</h5><div class="text-secondary small">Baris mengikuti alternatif dan kolom mengikuti kriteria terbaru dari database.</div></div><div class="d-flex flex-wrap gap-2"><span class="badge badge-benefit rounded-pill px-3 py-2">Benefit: lebih besar lebih baik</span><span class="badge badge-cost rounded-pill px-3 py-2">Cost: lebih kecil lebih baik</span></div></div></div>
@if($alternatives->isEmpty() || $criteria->isEmpty())
<div class="card"><div class="empty-state"><i class="bi bi-table"></i><h5 class="mt-3">Tabel penilaian belum dapat dibentuk</h5><p class="text-secondary">Tambahkan minimal satu kriteria dan alternatif terlebih dahulu.</p><div class="d-flex justify-content-center gap-2"><a href="{{ route('kriteria.create') }}" class="btn btn-outline-primary">Tambah Kriteria</a><a href="{{ route('alternatif.create') }}" class="btn btn-primary">Tambah Alternatif</a></div></div></div>
@else
<form method="POST" action="{{ route('assessments.store') }}">@csrf @method('PUT')
<div class="card"><div class="card-header d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-2"><div><h5 class="mb-1 fw-bold">Nilai Alternatif</h5><div class="small text-secondary">Semua sel wajib diisi dengan angka nol atau lebih besar.</div></div><div class="small text-secondary">{{ $alternatives->count() }} alternatif × {{ $criteria->count() }} kriteria = {{ $alternatives->count() * $criteria->count() }} nilai</div></div><div class="card-body p-0"><div class="table-responsive"><table class="table matrix-table align-middle"><thead><tr><th style="min-width:210px">Alternatif</th>@foreach($criteria as $criterion)<th style="min-width:155px"><div>{{ $criterion->code }} · {{ $criterion->name }}</div><div class="fw-normal text-lowercase">{{ $criterion->unit ?: 'tanpa satuan' }}</div><span class="badge mt-1 {{ $criterion->type === 'benefit' ? 'badge-benefit' : 'badge-cost' }}">{{ $criterion->type }}</span></th>@endforeach</tr></thead><tbody>@foreach($alternatives as $alternative)<tr><td><span class="code-badge me-2">{{ $alternative->code }}</span><strong>{{ $alternative->name }}</strong></td>@foreach($criteria as $criterion)@php($oldKey = "values.{$alternative->id}.{$criterion->id}")<td><input class="form-control assessment-input @error($oldKey) is-invalid @enderror" type="number" step="any" min="0" name="values[{{ $alternative->id }}][{{ $criterion->id }}]" value="{{ old($oldKey, data_get($values, $alternative->id.'.'.$criterion->id)) }}" required aria-label="Nilai {{ $alternative->code }} terhadap {{ $criterion->code }}">@error($oldKey)<div class="invalid-feedback">{{ $message }}</div>@enderror</td>@endforeach</tr>@endforeach</tbody></table></div></div><div class="card-footer bg-white border-top d-flex flex-column flex-sm-row justify-content-end gap-2 p-3"><button type="button" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#resetModal"><i class="bi bi-arrow-counterclockwise me-1"></i> Reset Semua</button><button class="btn btn-primary"><i class="bi bi-save me-1"></i> Simpan Nilai</button></div></div>
</form>
<div class="modal fade" id="resetModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Reset seluruh penilaian?</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">Semua nilai alternatif terhadap kriteria akan dikosongkan. Riwayat perhitungan sebelumnya tetap tersimpan.</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Batal</button><form method="POST" action="{{ route('assessments.reset') }}">@csrf @method('DELETE')<button class="btn btn-danger">Ya, Reset Nilai</button></form></div></div></div></div>
@endif
@endsection
