@extends('layouts.app')
@section('title', 'Proses TOPSIS')
@section('page-title', 'Proses TOPSIS')
@section('page-subtitle', 'Validasi kesiapan data dan jalankan seluruh tahapan perhitungan')
@section('content')
@if($latestRun)
<div class="{{ $isStale ? 'stale-banner' : 'fresh-banner' }} mb-4"><div class="d-flex gap-2"><i class="bi {{ $isStale ? 'bi-exclamation-triangle-fill' : 'bi-check-circle-fill' }}"></i><div><strong>{{ $isStale ? 'Perhitungan ulang diperlukan.' : 'Hasil terakhir masih mutakhir.' }}</strong><div class="small">Hasil terakhir: {{ $latestRun->name }} ({{ $latestRun->created_at->format('d/m/Y H:i') }}).</div></div></div></div>
@endif
<div class="row g-4"><div class="col-xl-7"><div class="card h-100"><div class="card-header"><h5 class="mb-0 fw-bold">Pemeriksaan Data</h5></div><div class="card-body">@foreach($readiness['checks'] as $key => $check)<div class="readiness-item"><span class="status-dot {{ $check['ok'] ? 'ok' : 'no' }}"><i class="bi {{ $check['ok'] ? 'bi-check-lg' : 'bi-x-lg' }}"></i></span><div><strong>{{ match($key){'alternatives'=>'Alternatif','criteria'=>'Kriteria','weights'=>'Normalisasi Bobot','assessments'=>'Kelengkapan Penilaian','divisors'=>'Pembagi Normalisasi'} }}</strong><div class="small text-secondary">{{ $check['message'] }}</div></div></div>@endforeach</div></div></div>
<div class="col-xl-5"><div class="card h-100"><div class="card-header"><h5 class="mb-0 fw-bold">Jalankan Perhitungan</h5></div><div class="card-body"><div class="row g-3 mb-4"><div class="col-6"><div class="p-3 rounded-3 bg-light"><div class="small text-secondary">Alternatif</div><div class="fs-3 fw-bold">{{ $readiness['alternative_count'] }}</div></div></div><div class="col-6"><div class="p-3 rounded-3 bg-light"><div class="small text-secondary">Kriteria</div><div class="fs-3 fw-bold">{{ $readiness['criterion_count'] }}</div></div></div><div class="col-6"><div class="p-3 rounded-3 bg-light"><div class="small text-secondary">Bobot Input</div><div class="fs-3 fw-bold">{{ decimal_value($readiness['total_weight'], 4) }}</div></div></div><div class="col-6"><div class="p-3 rounded-3 bg-light"><div class="small text-secondary">Nilai Terisi</div><div class="fs-3 fw-bold">{{ $readiness['assessment_count'] }}/{{ $readiness['expected_values'] }}</div></div></div></div><form method="POST" action="{{ route('process.store') }}">@csrf<div class="mb-3"><label class="form-label fw-semibold">Nama perhitungan</label><input name="name" value="{{ old('name') }}" class="form-control" maxlength="180" placeholder="Contoh: Evaluasi Kamera Fotografer Pemula"><div class="form-text">Opsional. Sistem akan membuat nama otomatis jika dikosongkan.</div></div><button class="btn btn-primary btn-lg w-100" @disabled(!$readiness['ready'])><i class="bi bi-calculator-fill me-2"></i>Hitung TOPSIS</button>@unless($readiness['ready'])<div class="small text-danger text-center mt-2">Tombol aktif setelah semua pemeriksaan berstatus siap.</div>@endunless</form></div></div></div></div>
<div class="card mt-4"><div class="card-header"><h5 class="mb-0 fw-bold">Tahapan yang Akan Dijalankan</h5></div><div class="card-body"><div class="row g-3">@foreach(['Matriks keputusan X','Normalisasi bobot','Pembagi normalisasi','Matriks normalisasi R','Normalisasi terbobot Y','Solusi ideal positif A+','Solusi ideal negatif A-','Jarak D+','Jarak D-','Nilai preferensi V','Perangkingan'] as $index => $stage)<div class="col-md-6 col-xl-4"><div class="d-flex gap-3 align-items-center p-3 border rounded-3"><span class="code-badge">{{ $index + 1 }}</span><strong class="small">{{ $stage }}</strong></div></div>@endforeach</div></div></div>
@endsection
